type Sport="NFL"|"NBA"|"MLB";

const content={
  NFL:{game:"Gridiron Grid",noun:"football",unit:"player",examples:"teams, Pro Bowls, championships, passing, rushing, receiving, and defensive milestones",tip:"Remember short late-career stops and franchise relocations.",href:"/"},
  NBA:{game:"NBA Grid",noun:"basketball",unit:"player",examples:"teams, career scoring ranks, scoring titles, All-Star selections, awards, and three-point milestones",tip:"Separate awards won anywhere in a career from statistics recorded with one particular team.",href:"/nba-grid/"},
  MLB:{game:"MLB Grid",noun:"baseball",unit:"player",examples:"clubs, career hits, home runs, stolen bases, MVP awards, Cy Young awards, and World Series titles",tip:"Trades, late-career appearances, and historic franchise names often unlock the hardest squares.",href:"/mlb-grid/"},
};

export function SportSeoContent({sport}:{sport:Sport}) {
  const item=content[sport];
  const faq=[
    [`What is ${item.game}?`,`${item.game} is a free daily ${item.noun} trivia puzzle. Drag one of nine player cards into each square by matching the row team with the column career condition.`],
    ["When does the puzzle change?","A new board, set of clues, and nine-player pool appears every day at 8 PM Eastern Time."],
    ["Can a player fit more than one square?","Yes. Versatile players often satisfy several squares, but each card can be used only once, so placement order matters."],
    ["Where can I see yesterday’s answers?","Open Past Answers beneath the game. Each completed daily board has its own archive entry and playable URL."],
  ];
  const schema={"@context":"https://schema.org","@type":"FAQPage","mainEntity":faq.map(([question,answer])=>({"@type":"Question","name":question,"acceptedAnswer":{"@type":"Answer","text":answer}}))};
  return <article className="guide sport-seo">
    <section className="intro-grid"><div><p className="section-kicker">{sport} GRID GUIDE</p><h2>How the daily puzzle works</h2></div><div className="lead-copy"><p>Match all nine player cards to a 3×3 board built from changing teams and difficult career statistics.</p><p>Every row represents a franchise and every column represents a measurable condition such as {item.examples}. A correct card must satisfy both. Because the player pool contains exactly nine names and cards cannot be reused, the puzzle rewards planning as much as recall.</p></div></section>
    <section className="steps"><div><b>01</b><h3>Read every clue</h3><p>Check all three teams and all three statistical thresholds before moving a card.</p></div><div><b>02</b><h3>Place the specialists</h3><p>Use players who fit only one obvious square first. Save flexible stars for later.</p></div><div><b>03</b><h3>Return tomorrow</h3><p>The official result appears after the puzzle closes, with a permanent archive page.</p></div></section>
    <section className="daily"><p className="section-kicker">DAILY STRATEGY</p><h2>Think across the whole career</h2><div className="daily-grid"><p>{item.tip} The row condition normally asks whether a player officially appeared for the franchise, while the column condition may describe an achievement from any point in his career.</p><p>Do not rush the most famous name into the first square it fits. Look for the least flexible cards, solve those first, and preserve multi-team stars for the intersections with fewer alternatives.</p></div><p className="content-links"><a href={`${item.href}how-to-play/`}>Read the complete rules →</a><a href={`${item.href}strategies/`}>Open the strategy guide →</a><a href={`${item.href}archive/`}>Browse past answers →</a></p></section>
    <section className="faq"><p className="section-kicker">FAQ</p><h2>{sport} Grid questions</h2><div className="faq-list">{faq.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  </article>;
}

export function SportArticlePage({sport,type}:{sport:Sport;type:"how"|"strategies"}) {
  const item=content[sport];
  const isHow=type==="how";
  return <main className="content-page"><header className="archive-header"><a className="brand" href="/"><span className="brand-ball">G</span><span>GRIDIRON<span>GRID</span></span></a><a href={item.href}>← Play today&apos;s {sport} Grid</a></header><article><p className="section-kicker">{sport} GRID FIELD GUIDE</p><h1>{isHow?`How to play ${item.game}`:`${item.game} strategies`}</h1><p className="content-lead">{isHow?`Learn the rules, card controls, scoring, daily reset, and archive system for the ${sport} daily grid.`:`A practical approach for solving difficult ${sport} team-and-stat intersections without wasting a player card.`}</p>
  {isHow?<><h2>Read the board before the player pool</h2><p>The board has three team rows and three statistical columns. A card belongs in a square only when that player represented the row franchise and also meets the column condition. The condition may come from any point in the player’s career unless the clue explicitly says it must have happened with that team.</p><h2>Drag, tap, and submit</h2><p>On desktop, drag a player card from the pool into an empty square. On a phone or tablet, tap the card and then tap the destination. A correct placement stays on the board and the card leaves the pool. Each player can appear once.</p><h2>Daily games and archived URLs</h2><p>The teams, clues, and nine-player pool change at 8 PM Eastern Time. When the board closes, its official answers are published in the archive. Every date also has a permanent game URL, so old puzzles remain playable and shareable.</p></>:<><h2>Solve constrained cards first</h2><p>Scan the nine names and identify players with one obvious franchise connection or one rare achievement. Place those cards first. Superstars and well-traveled veterans often fit several locations and should remain available until the board narrows.</p><h2>Separate team history from career achievements</h2><p>A player generally needs an official appearance for the row team, but a career award or statistical milestone can come from another season and another club. This distinction creates many of the game’s hardest but fairest answers.</p><h2>Use elimination, not guessing</h2><p>If three cards remain, compare every open row and column before moving one. A card that fits two open squares is less urgent than a card that fits only one. Treat the final board like a logic puzzle rather than nine unrelated trivia questions.</p></>}
  <nav className="article-links"><a href={item.href}>Play today →</a><a href={`${item.href}archive/`}>Past answers →</a><a href={isHow?`${item.href}strategies/`:`${item.href}how-to-play/`}>{isHow?"Strategy guide →":"Complete rules →"}</a></nav></article></main>;
}
